# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bash_Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bash_command', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=200)),
                ('man_page_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cmd_Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_command', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=200)),
                ('man_page_url', models.CharField(max_length=100)),
                ('bash_translation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bash_to_cmd_app.Bash_Command')),
            ],
        ),
        migrations.AddField(
            model_name='bash_command',
            name='cmd_translation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bash_to_cmd_app.Cmd_Command'),
        ),
    ]
