# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bash_to_cmd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bash_command',
            name='cmd_translation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bash_to_cmd_app.Cmd_Command'),
        ),
    ]
